routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::post('/help', 'HomeController@help')->name('help-form');

/* Booking Routes */

Route::group(['prefix' => 'booking'], function () {
    
    Route::get('/', 'BookingController@index')->name('booking.index');
    
    Route::get('/search/hospitals', 'BookingController@searchHospitals')->name('booking.search.hospitals');
    Route::get('/search/services', 'BookingController@searchServices')->name('booking.search.services');
    Route::get('/search/bundles', 'BookingController@searchBundles')->name('booking.search.bundles');
    
});

Route::get('admin/services/get-service-categories', 'ServiceController@getServiceCategories');

Route::group(['prefix' => 'categories'], function() {
    Route::get('/service_categories/{category}', 'CategoryController@getServiceCategories');
});

/* Hospital details routes */

Route::get('hospitals/{hospital}/{bundle}', 'HospitalController@bundle')->name('hospitals.bundle');

/* Profile routes */

Route::group([
    'prefix' => 'profile',
    'middleware' => 'auth'
], function () {
    Route::get('/', 'ProfileController@index')->name('profile.index');
});

/* Shopping Cart Routes  */

Route::group([
    'prefix' => 'cart',
    'middleware' => 'auth'
], function () {
    
    Route::get('/', 'CartController@index')->name('cart.index');
    
    Route::get('/add/{type}/{id}', 'CartController@store')->name('cart.add');
    
    Route::get('/delete/{type}/{id}', 'CartController@destroy')->name('cart.delete');

    Route::get('/send', 'OrdersController@create')->name('cart.send');
    
});

/* Orders routes */

Route::group([
    'prefix' => 'orders',
    'middleware' => 'auth'
], function () {
    Route::post('/create', 'OrdersController@create')->name('order.create');
});

Route::group([], function () {
    
    Route::get('/faq', 'PagesController@faq')->name('pages.faq');
    
    Route::get('/articles', 'PagesController@articles')->name('pages.articles');
    
    Route::get('/articles/{id}', 'PagesController@article')->name('pages.articles.show');
    
    Route::get('/news', 'PagesController@news')->name('pages.news');
    
});

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin']
], function() {
   
    Route::get('/', 'AdminController@index')->name('admin.index');
    
    Route::resource('/news', 'NewsController');
    Route::resource('/articles', 'ArticleController');
    Route::resource('/faq', 'FaqController');
    Route::resource('/hospitals', 'HospitalController');
    Route::resource('/categories', 'CategoryController');
    Route::get('/services/get_by_category', 'ServiceController@getByCategory');
    Route::resource('/services', 'ServiceController');
    Route::resource('/bundles', 'BundleController');
    Route::post('/bundles/{id}/duplicate', 'BundleController@duplicate')->name('bundles.duplicate');
    Route::resource('/users', 'UserController');
    Route::resource('/cities', 'CityController');
    Route::resource('/orders', 'OrdersController', ['except' => ['create', 'store']]);
    
});

Route::get('/hospitals/get-by-city', 'HospitalController@getByCityId')->name('hospitals.get-by-city');
Route::get('/services/get-by-service-category', 'ServiceController@getByServiceCategoryId')->name('services.get-by-service-category');

app/Hospital.php
<?php

namespace App;

use App\Booking\QueryFilter;
use Illuminate\Database\Eloquent\Model;
use App\Service;
use App\Bundle;
use App\City;

class Hospital extends Model
{
    protected $casts = [
        'gallery' => 'array'
    ];
    
    protected $fillable = ['name', 'description', 'city_id', 'category_id'];
    
    public function services() {
        return $this->belongsToMany(Service::class)->withPivot('price');
    }
    
    public function bundles() {
        return $this->hasMany(Bundle::class);
    }
    
    public function city() {
        return $this->belongsTo(City::class);
    }
    
    public function category() {
        return $this->belongsTo(Category::class);
    }
    
    public function scopeFilter($query, QueryFilter $filters)
    {
        return $filters->apply($query);
    }
}

app/Http/Controllers/HospitalController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use App\City;
use App\ServiceCategory;
use App\Service;
use App\Bundle;
use App\Hospital;
use Illuminate\Support\Facades\Validator;

class HospitalController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hospitals = Hospital::orderBy('id', 'desc')->get();
    
        return view('admin.hospitals.index', ['hospitals' => $hospitals]);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $bundles = Bundle::all();
        $services = Service::where('type', '!=', 'default')->get();
        $cities = City::all();
        $categories = Category::all();
        
        return view('admin.hospitals.create', [
            'services' => $services,
            'bundles' => $bundles,
            'categories' => $categories,
            'cities' => $cities
        ]);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'image' => 'file|image',
            'gallery.*' => 'file|image'
        ]);
        
        $input = $request->all();
        
        $hospital = new Hospital();
        
        $hospital->name = $input['name'];
        $hospital->description = $input['description'];
        $hospital->image = null;
        $hospital->city_id = $input['city_id'];
        $hospital->category_id = $input['category_id'];
        $hospital->notes = $input['notes'];
        $hospital->visa_support = $input['visa_support'];
        $hospital->additional_transfer = $input['additional_transfer'];
        $hospital->international = !empty($input['international']);
        if($request->has('image')) {
            $hospital->image = $request->file('image')->store('hospitals', 'public');
        }

        $gallery = [];

        if($request->has('gallery')) {
            if(is_array($request->file('gallery'))) {
                foreach ($request->file('gallery') as $file) {
                    $gallery[] = $file->store('hospitals', 'public');
                }
            } else {
                $gallery[] = $request->file('gallery')->store('hospitals', 'public');
            }
        }

        $hospital->gallery = $gallery;

        $hospital->save();
        
        return redirect()->route('hospitals.edit', ['id' => $hospital['id']]);
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $hospital = Hospital::with('services')
            ->where('id', '=', $id)
            ->first();
        
        return response()->json($hospital->toArray());
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $hospital = Hospital::find($id);
        $bundles = Bundle::all();
        $services = Service::where('category_id', '=', $hospital->category_id)
            ->where('type', '!=', 'default')
            ->orWhere('type', '=', null)
            ->get();
        $cities = City::all();
        $categories = Category::all();
        
        return view('admin.hospitals.edit', [
            'hospital' => $hospital,
            'services' => $services,
            'bundles' => $bundles,
            'categories' => $categories,
            'cities' => $cities
        ]);
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'image' => 'file|image',
            'gallery.*' => 'file|image'
        ]);

        $hospital = Hospital::find($id);
        $services = [];
        
        $input = $request->all();
    
        $hospital->name = $input['name'];
        $hospital->description = $input['description'];
        $hospital->city_id = $input['city_id'];
        $hospital->notes = $input['notes'];
        $hospital->visa_support = $input['visa_support'];
        $hospital->additional_transfer = $input['additional_transfer'];
        $hospital->international = !empty($input['international']);

        if($request->file('image')) {
            $hospital->image = $request->file('image')->store('hospitals', 'public');
        }


        if ($request->file('gallery')) {
            $gallery = [];

            if(is_array($request->file('gallery'))) {
                foreach ($request->file('gallery') as $file) {
                    $gallery[] = $file->store('hospitals', 'public');
                }
            } else {
                $gallery[] = $request->file('gallery')->store('hospitals', 'public');
            }

            $hospital->gallery = $gallery;
        }

        $hospital->save();
        
        if(isset($input['services'])) {
            foreach ($input['services'] as $service) {
                $service_id = explode(':', $service)[0];
                $service_price = explode(':', $service)[1];
        
                $services[$service_id] = ['price' => $service_price];
            }
    
            $hospital->services()->sync($services);
        }
        
        return back();
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Hospital::destroy($id);
        
        return back();
    }
    
    public function getByCityId(Request $request)
    {
        $this->validate($request, [
            'id' => 'required|numeric'
        ]);
        
        $hospitals = Hospital::where('city_id', $request->get('id'))->get()->toArray();
        
        return response()->json($hospitals);
    }

    public function bundle(Hospital $hospital, Bundle $bundle)
    {
        return view('hospitals.bundle', compact('hospital', 'bundle'));
    }
}

resources/views/admin/hospitals/create.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <h1>Create Hospital</h1>

        @if (count($errors) > 0)
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <form action="{{ route('hospitals.store') }}" method="POST" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('POST') }}
            <div class="form-group">
                <label for="hospital-name">Название</label>
                <input type="text" name="name" id="hospital-name" class="form-control">
            </div>

            <div class="form-group">
                <label for="city">Город</label>
                <select name="city_id" id="city" class="form-control">
                    @foreach($cities as $city)
                        <option value="{{ $city['id'] }}">{{ $city['name'] }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="category">Категория</label>
                <select name="category_id" id="category" class="form-control">
                    @foreach($categories as $category)
                        <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="visa_support">Визовая поддержка</label>
                <input type="text" name="visa_support" id="visa_support" class="form-control">
            </div>

            <div class="checkbox">
                <label>
                    <input type="checkbox" name="international" value="true">
                    <span>Международный отдел</span>
                </label>
            </div>

            <div class="form-group">
                <label for="image">Главная фотка</label>
                <input type="file" name="image" id="image" accept="image/png,image/jpeg,image/gif">
            </div>

            <div class="form-group">
                <label for="gallery">Фотографии для галереи</label>
                <input type="file" name="gallery[]" id="gallery" accept="image/png,image/jpeg,image/gif" multiple>
            </div>

            <div class="form-group">
                <label for="hospital-description">Описание</label>
                <textarea rows="10" name="description" id="hospital-description" class="form-control html-editor"></textarea>
            </div>

            <div class="form-group">
                <label for="additional_transfer">Дополнительный трансфер</label>
                <textarea rows="10" name="additional_transfer" id="additional_transfer" class="form-control html-editor"></textarea>
            </div>

            <div class="form-group">
                <label for="hospital-notes">Примечания</label>
                <textarea rows="10" name="notes" id="hospital-notes" class="form-control html-editor"></textarea>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>
    </section>
@endsection

resources/views/admin/hospitals/edit.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
                <a href="#info" aria-controls="info" role="tab" data-toggle="tab">Информация о госпитале</a>
            </li>

            <li role="presentation">
                <a href="#bundles" aria-controls="bundles" role="tab" data-toggle="tab">Бандлы</a>
            </li>

            <li role="presentation">
                <a href="#services" aria-controls="services" role="tab" data-toggle="tab">Услуги</a>
            </li>
        </ul>

        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="info">
                <h1>Edit Hospital</h1>

                @if (count($errors) > 0)
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form action="{{ route('hospitals.update', ['id' => $hospital['id']]) }}" method="POST" id="hospital-edit" enctype="multipart/form-data">
                    {{ csrf_field() }}
                    {{ method_field('PUT') }}
                    <div class="form-group">
                        <label for="hospital-name">Название</label>
                        <input type="text" name="name" id="hospital-name" class="form-control" value="{{ $hospital['name'] }}">
                    </div>

                    <div class="form-group">
                        <label for="city">Город</label>
                        <select name="city_id" id="city" class="form-control">
                            @foreach($cities as $city)
                                <option @if($hospital['city_id'] == $city['id']) selected @endif value="{{ $city['id'] }}">{{ $city['name'] }}</option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="category">Категория</label>
                        <input type="text" class="form-control" value="{{ $hospital->category->name }}" disabled>
                    </div>

                    <div class="form-group">
                        <label>Визовая поддержка</label>
                        <input type="text" name="visa_support" class="form-control" value="{{ $hospital['visa_support'] }}">
                    </div>

                    <div class="checkbox">
                        <label>
                            <input type="checkbox" name="international" value="true" @if($hospital['international']) checked @endif>
                            <span>Международный отдел</span>
                        </label>
                    </div>

                    <div class="form-group">
                        <label for="image">Главная фотка</label>
                        <input type="file" name="image" id="image" accept="image/png,image/jpeg,image/gif">
                        <img src="{{ asset('storage/' . $hospital->image) }}" class="img-responsive" alt="">
                    </div>

                    <div class="form-group">
                        <label for="gallery">Фотографии для галереи</label>
                        <input type="file" name="gallery[]" id="gallery" accept="image/png,image/jpeg,image/gif" multiple>
                    </div>

                    <div class="form-group">
                        <div class="row">
                            @if(count($hospital->gallery))
                                @foreach($hospital->gallery as $item)
                                    <div class="col-md-3">
                                        <img src="{{ asset('storage/' . $item) }}" alt="" class="img-responsive">
                                    </div>
                                @endforeach
                            @endif
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="hospital-description">Описание</label>
                        <textarea rows="10" name="description" id="hospital-description" class="form-control html-editor">{{ $hospital['description'] }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="additional_transfer">Дополнительный трансфер</label>
                        <textarea rows="10" name="additional_transfer" id="additional_transfer" class="form-control html-editor">{{ $hospital['additional_transfer'] }}</textarea>
                    </div>

                    <div class="form-group">
                        <label for="hospital-notes">Примечания</label>
                        <textarea rows="10" name="notes" id="hospital-notes" class="form-control html-editor">{{ $hospital['notes'] }}</textarea>
                    </div>

                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>

            <div role="tabpanel" class="tab-pane" id="bundles">
                <h2>Бандлы</h2>
                <div class="form-group">
                    <form action="{{ route('bundles.create') }}" method="POST">
                        {{ csrf_field() }}
                        {{ method_field('GET') }}
                        <input type="hidden" name="hospital_id" value="{{ $hospital['id'] }}">
                        <button type="submit" class="btn btn-primary">Создать бандл</button>
                    </form>
                </div>
                <table class="table table-striped table-bordered">
                    <thead>
                    <tr>
                        <td>Название</td>
                        <td>Редактировать</td>
                        <td>Дублировать</td>
                        <td>Удалить</td>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach($hospital->bundles as $bundle)
                        <tr>
                            <td>{{ $bundle['name'] }}</td>
                            <td>
                                <form action="{{ route('bundles.edit', ['id' => $bundle['id']]) }}" method="POST">
                                    {{ csrf_field() }}
                                    {{ method_field('GET') }}
                                    <input type="hidden" name="hospital_id" value="{{ $hospital['id'] }}">
                                    <input type="submit" class="btn btn-primary" value="Редактировать" />
                                </form>
                            </td>

                            <td>
                                <form action="{{ route('bundles.duplicate', ['id' => $bundle['id']]) }}" method="POST">
                                    {{ method_field('POST') }}
                                    {{ csrf_field() }}
                                    <input type="submit" class="btn btn-primary" value="Дублировать">
                                </form>
                            </td>

                            <td>
                                <form action="{{ route('bundles.destroy', ['id' => $bundle['id']]) }}" method="POST">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <input type="submit" class="btn btn-danger" value="Удалить" />
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            <div role="tabpanel" class="tab-pane" id="services">
                <h2>Услуги</h2>
                @foreach($hospital->category->service_categories as $service_category)
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title">{{ $service_category['name'] }}</h3>
                        </div>
                        <div class="panel-body">
                            <ul class="list-group">
                                @foreach($services as $service)
                                    @if($service['service_category_id'] == $service_category['id'])
                                        <li class="list-group-item">
                                            <label>{{ $service['name_ru'] }}
                                                <input
                                                        type="text"
                                                        class="form-control service-data"
                                                        data-service-id="{{ $service['id'] }}"
                                                        value="{{ $hospital->services()->where('id', $service['id'])->first()->pivot->price or '' }}"
                                                >
                                            </label>
                                        </li>
                                    @endif
                                @endforeach
                            </ul>
                        </div>
                    </div>
                @endforeach
            </div>
        </div>
    </section>
@endsection

resources/views/admin/hospitals/index.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <h1>Hospitals</h1>

        <div class="form-group">
            <a href="{{ route('hospitals.create') }}" class="btn btn-primary">Создать</a>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <td>Название</td>
                <td>Описание</td>
                <td>Город</td>
                <td>Категория</td>
                <td>Редактировать</td>
                <td>Удалить</td>
            </tr>
            </thead>

            <tbody>
            @foreach($hospitals as $hospital)
                <tr>
                    <td>{{ $hospital['name'] }}</td>
                    <td>{{ str_limit($hospital['description'], 50) }}</td>
                    <td>{{ $hospital->city['name'] }}</td>
                    <td>{{ $hospital->category['name'] }}</td>
                    <td><a class="btn btn-primary" href="{{ route('hospitals.edit', ['id' => $hospital['id']]) }}">Редактировать</a></td>
                    <td>
                        <form action="{{ route('hospitals.destroy', ['id' => $hospital['id']]) }}" method="POST">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <input type="submit" class="btn btn-danger" value="Удалить">
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </section>
@endsection