routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::post('/help', 'HomeController@help')->name('help-form');

/* Booking Routes */

Route::group(['prefix' => 'booking'], function () {
    
    Route::get('/', 'BookingController@index')->name('booking.index');
    
    Route::get('/search/hospitals', 'BookingController@searchHospitals')->name('booking.search.hospitals');
    Route::get('/search/services', 'BookingController@searchServices')->name('booking.search.services');
    Route::get('/search/bundles', 'BookingController@searchBundles')->name('booking.search.bundles');
    
});

Route::get('admin/services/get-service-categories', 'ServiceController@getServiceCategories');

Route::group(['prefix' => 'categories'], function() {
    Route::get('/service_categories/{category}', 'CategoryController@getServiceCategories');
});

/* Hospital details routes */

Route::get('hospitals/{hospital}/{bundle}', 'HospitalController@bundle')->name('hospitals.bundle');

/* Profile routes */

Route::group([
    'prefix' => 'profile',
    'middleware' => 'auth'
], function () {
    Route::get('/', 'ProfileController@index')->name('profile.index');
});

/* Shopping Cart Routes  */

Route::group([
    'prefix' => 'cart',
    'middleware' => 'auth'
], function () {
    
    Route::get('/', 'CartController@index')->name('cart.index');
    
    Route::get('/add/{type}/{id}', 'CartController@store')->name('cart.add');
    
    Route::get('/delete/{type}/{id}', 'CartController@destroy')->name('cart.delete');

    Route::get('/send', 'OrdersController@create')->name('cart.send');
    
});

/* Orders routes */

Route::group([
    'prefix' => 'orders',
    'middleware' => 'auth'
], function () {
    Route::post('/create', 'OrdersController@create')->name('order.create');
});

Route::group([], function () {
    
    Route::get('/faq', 'PagesController@faq')->name('pages.faq');
    
    Route::get('/articles', 'PagesController@articles')->name('pages.articles');
    
    Route::get('/articles/{id}', 'PagesController@article')->name('pages.articles.show');
    
    Route::get('/news', 'PagesController@news')->name('pages.news');
    
});

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin']
], function() {
   
    Route::get('/', 'AdminController@index')->name('admin.index');
    
    Route::resource('/news', 'NewsController');
    Route::resource('/articles', 'ArticleController');
    Route::resource('/faq', 'FaqController');
    Route::resource('/hospitals', 'HospitalController');
    Route::resource('/categories', 'CategoryController');
    Route::get('/services/get_by_category', 'ServiceController@getByCategory');
    Route::resource('/services', 'ServiceController');
    Route::resource('/bundles', 'BundleController');
    Route::post('/bundles/{id}/duplicate', 'BundleController@duplicate')->name('bundles.duplicate');
    Route::resource('/users', 'UserController');
    Route::resource('/cities', 'CityController');
    Route::resource('/orders', 'OrdersController', ['except' => ['create', 'store']]);
    
});

Route::get('/hospitals/get-by-city', 'HospitalController@getByCityId')->name('hospitals.get-by-city');
Route::get('/services/get-by-service-category', 'ServiceController@getByServiceCategoryId')->name('services.get-by-service-category');

app/Service.php
<?php

namespace App;

use App\Booking\QueryFilter;
use Illuminate\Database\Eloquent\Model;

use App\Category;

class Service extends Model
{
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    
    public function service_category()
    {
        return $this->belongsTo(ServiceCategory::class, 'service_category_id');
    }
    
    public function scopeFilter($query, QueryFilter $filters)
    {
        return $filters->apply($query);
    }
}

app/Http/Controllers/ServiceController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Repositories\ServiceImporter;
use App\ServiceCategory;
use Illuminate\Http\Request;
use App\Service;

class ServiceController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $sort_by = $request->get('sort_by') ?? 'id';
        
        $direction = $request->get('direction') ?? 'asc';
        
        $categories = Category::all();
    
    
        $category_id = $request->get('category_id') ?? false;
        
        $service_category_id = $request->get('service_category_id') ?? false;
    
        $service_categories = $categories->first();
        
        $services = Service::orderBy($sort_by, $direction);
        
        if($category_id) {
            $services->where('category_id', $category_id);
            $service_categories = $categories->where('id', $category_id)->first();
        }

        if($service_category_id) {
            $services->where('service_category_id', $service_category_id);
        }
        
        $services = $services->get();
        
        $service_categories = $service_categories->service_categories;
        
        return view('admin.services.index', [
            'services' => $services,
            'categories' => $categories,
            'service_categories' => $service_categories
        ]);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        
        $service_categories = $categories->first()->service_categories;
        
        return view('admin.services.create', [
            'categories' => $categories,
            'service_categories' => $service_categories
        ]);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        
        $service = new Service();
    
        $service->name_ru = $input['name_ru'];
        $service->description = $input['description'];
        $service->type = $input['type'] === 'null' ? null : $input['type'];
        $service->category_id = $input['category_id'];
        $service->service_category_id = $input['service_category_id'];
        $service->gender = $input['gender'];
        
        $service->save();
        
        
    
        return redirect()->route('services.index');
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $service = Service::find($id);
    
        return view('admin.services.edit', ['service' => $service]);
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
    
        $service = Service::find($id);
        
        $service->name_ru = $input['name_ru'];
        $service->description = $input['description'];
    
        $service->type = $input['type'] === 'null' ? null : $input['type'];
        $service->gender = $input['gender'];
        
        $service->save();
        
        return redirect()->route('services.index');
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Service::destroy($id);
        
        return redirect()->route('services.index');
    }
    
    public function getServiceCategories(Request $request)
    {
        $category_id = $request->get('category_id');
        
        $service_categories = ServiceCategory::where('category_id', $category_id)->get();
        
        return view('admin.services.service-categories', [
            'service_categories' => $service_categories
        ]);
    }
    
    public function getByServiceCategoryId(Request $request)
    {
        $this->validate($request, [
            'id' => 'required|numeric'
        ]);
        
        $category_id = $request->get('id');
    
        $services = Service::where('service_category_id', $category_id)->get()->toArray();
        
        return response()->json($services);
    }
}

resources/views/admin/services/create.blade.php
@extends('layouts.app')

@section('content')
    <section>

        <h1>Редактировать сервис</h1>

        <form action="{{ route('services.store') }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('POST') }}
            <div class="form-group">
                <label for="service-name">Название</label>
                <input type="text" id="service-name" class="form-control" name="name_ru">
            </div>

            <div class="form-group">
                <label for="service-description">Описание</label>
                <textarea id="service-description" class="form-control html-editor" name="description"></textarea>
            </div>

            <div class="form-group">
                <label for="service-category">Категория</label>
                <select name="category_id" id="service-category" class="form-control">
                    @foreach($categories as $category)
                        <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="service-subcategory">Подкатегория</label>
                <select name="service_category_id" id="service-subcategory" class="form-control">
                    @foreach($service_categories as $category)
                        <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <h3>Тип</h3>
                <div class="radio">
                    <label>
                        <input type="radio" name="type" value="default">
                        Default
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio" name="type" value="popular">
                        Popular
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio" name="type" value="null" checked>
                        None
                    </label>
                </div>
            </div>

            <div class="form-group">
                <h3>Пол</h3>

                <div class="radio">
                    <label>
                        <input type="radio" name="gender" value="general" checked>
                        Общий
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio" name="gender" value="male">
                        Мужской
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio" name="gender" value="female">
                        Женский
                    </label>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>

    </section>
@endsection

resources/views/admin/services/edit.blade.php
@extends('layouts.app')

@section('content')
    <section>

        <h1>Редактировать сервис</h1>

        <form action="{{ route('services.update', ['id' => $service['id']]) }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="form-group">
                <label for="service-name">Название</label>
                <input type="text" id="service-name" class="form-control" name="name_ru" value="{{ $service['name_ru'] }}">
            </div>

            <div class="form-group">
                <label for="service-description">Описание</label>
                <textarea id="service-description" class="form-control html-editor" name="description">{{ $service['description'] }}</textarea>
            </div>

            <div class="form-group">
                <label for="service-category">Категория</label>
                <input type="text" id="service-category" class="form-control" value="{{ $service->category['name'] }}" disabled>
            </div>

            <div class="form-group">
                <label for="service-subcategory">Подкатегория</label>
                <input type="text" id="service-subcategory" class="form-control" value="{{ $service->service_category['name'] }}" disabled>
            </div>

            <div class="form-group">
                <h3>Тип</h3>
                <div class="radio">
                    <label>
                        <input type="radio" name="type" value="default" @if($service['type'] == 'default') checked @endif>
                        Default
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio" name="type" value="popular" @if($service['type'] == 'popular') checked @endif>
                        Popular
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio" name="type" value="null" @if($service['type'] == null) checked @endif>
                        None
                    </label>
                </div>
            </div>

            <div class="form-group">
                <h3>Пол</h3>
                <div class="radio">
                    <label>
                        <input type="radio" name="gender" value="male" @if($service['gender'] == 'male') checked @endif>
                        Мужской
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio" name="gender" value="female" @if($service['gender'] == 'female') checked @endif>
                        Женский
                    </label>
                </div>

                <div class="radio">
                    <label>
                        <input type="radio" name="gender" value="general" @if($service['gender'] == 'general') checked @endif>
                        Общий
                    </label>
                </div>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>

    </section>
@endsection

resources/views/admin/services/import.blade.php
@extends('layouts.app')

@section('content')
    <h2>Загрузка сервисов</h2>
    <form action="/admin/services/import" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}

        <div class="form-group">
            <label for="services">File</label>
            <input type="file" name="services">
        </div>

        <div class="form-group">
            <input class="btn btn-default" type="submit" value="Submit">
        </div>
    </form>

    @if(count($errors) > 0)
        <div class="alert alert-danger">
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </div>
    @endif

    @if(session('message'))
        <div class="alert alert-success">
            <span>{{ session('message') }}</span>
        </div>
    @endif
@endsection

resources/views/admin/services/index.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <h1>Services</h1>

        <div class="form-group">
            <a href="{{ route('services.create') }}" class="btn btn-primary">Создать</a>
        </div>

        <form class="" method="GET">
            <div class="form-group">
                <label for="service-category">Категория:</label>
                <select name="category_id" id="service-category" class="form-control js-services-index">
                    <option value="0">- Все -</option>
                    @foreach($categories as $category)
                        <option value="{{ $category['id'] }}" @if(request()->get('category_id') == $category['id']) selected @endif>
                            {{ $category['name'] }}
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="service-subcategory">Подкатегория:</label>
                <select name="service_category_id" id="service-subcategory" class="form-control">
                    <option value="0">- Все -</option>
                    @foreach($service_categories as $category)
                        <option value="{{ $category['id'] }}">
                            {{ $category['name'] }}
                        </option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <input type="submit" class="btn btn-primary" value="Отфильтровать">
            </div>
        </form>

        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <td class="col-md-2">Название
                    <a href="{{ route('services.index', ['sort_by' => 'name_ru', 'direction' => 'asc']) }}">↑</a>
                    <a href="{{ route('services.index', ['sort_by' => 'name_ru', 'direction' => 'desc']) }}">↓</a>
                </td>
                <td class="col-md-1">Описание
                    <a href="{{ route('services.index', ['sort_by' => 'description', 'direction' => 'asc']) }}">↑</a>
                    <a href="{{ route('services.index', ['sort_by' => 'description', 'direction' => 'desc']) }}">↓</a>
                </td>
                <td class="col-md-1">Категория
                    <a href="{{ route('services.index', ['sort_by' => 'category_id', 'direction' => 'asc']) }}">↑</a>
                    <a href="{{ route('services.index', ['sort_by' => 'category_id', 'direction' => 'desc']) }}">↓</a>
                </td>
                <td class="col-md-1">Тип
                    <a href="{{ route('services.index', ['sort_by' => 'type', 'direction' => 'asc']) }}">↑</a>
                    <a href="{{ route('services.index', ['sort_by' => 'type', 'direction' => 'desc']) }}">↓</a>
                </td>
                <td class="col-md-1">Подкатегория
                    <a href="{{ route('services.index', ['sort_by' => 'service_category_id', 'direction' => 'asc']) }}">↑</a>
                    <a href="{{ route('services.index', ['sort_by' => 'service_category_id', 'direction' => 'desc']) }}">↓</a>
                </td>
                <td class="col-md-2">Создано
                    <a href="{{ route('services.index', ['sort_by' => 'created_at', 'direction' => 'asc']) }}">↑</a>
                    <a href="{{ route('services.index', ['sort_by' => 'created_at', 'direction' => 'desc']) }}">↓</a>
                </td>
                <td class="col-md-1">Редактировать</td>
                <td class="col-md-1">Удалить</td>
            </tr>
            </thead>

            <tbody>
            @foreach($services as $service)
                <tr>
                    <td>{{ $service['name_ru'] }}</td>
                    <td>{{ str_limit($service['description'], 50) }}</td>
                    <td>{{ $service->category['name'] }}</td>
                    <td>{{ $service['type'] }}</td>
                    <td>{{ $service->service_category['name'] }}</td>
                    <td>{{ $service['created_at'] }}</td>
                    <td><a class="btn btn-primary" href="{{ route('services.edit', ['id' => $service['id']]) }}">Редактировать</a></td>
                    <td>
                        <form action="{{ route('services.destroy', ['id' => $service['id']]) }}" method="POST">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                            <input type="submit" class="btn btn-danger" value="Удалить">
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </section>
@endsection

resources/views/admin/services/service-categories.blade.php
@foreach($service_categories as $category)
    <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>
@endforeach