routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');

Route::post('/help', 'HomeController@help')->name('help-form');

/* Booking Routes */

Route::group(['prefix' => 'booking'], function () {
    
    Route::get('/', 'BookingController@index')->name('booking.index');
    
    Route::get('/search/hospitals', 'BookingController@searchHospitals')->name('booking.search.hospitals');
    Route::get('/search/services', 'BookingController@searchServices')->name('booking.search.services');
    Route::get('/search/bundles', 'BookingController@searchBundles')->name('booking.search.bundles');
    
});

Route::get('admin/services/get-service-categories', 'ServiceController@getServiceCategories');

Route::group(['prefix' => 'categories'], function() {
    Route::get('/service_categories/{category}', 'CategoryController@getServiceCategories');
});

/* Hospital details routes */

Route::get('hospitals/{hospital}/{bundle}', 'HospitalController@bundle')->name('hospitals.bundle');

/* Profile routes */

Route::group([
    'prefix' => 'profile',
    'middleware' => 'auth'
], function () {
    Route::get('/', 'ProfileController@index')->name('profile.index');
});

/* Shopping Cart Routes  */

Route::group([
    'prefix' => 'cart',
    'middleware' => 'auth'
], function () {
    
    Route::get('/', 'CartController@index')->name('cart.index');
    
    Route::get('/add/{type}/{id}', 'CartController@store')->name('cart.add');
    
    Route::get('/delete/{type}/{id}', 'CartController@destroy')->name('cart.delete');

    Route::get('/send', 'OrdersController@create')->name('cart.send');
    
});

/* Orders routes */

Route::group([
    'prefix' => 'orders',
    'middleware' => 'auth'
], function () {
    Route::post('/create', 'OrdersController@create')->name('order.create');
});

Route::group([], function () {
    
    Route::get('/faq', 'PagesController@faq')->name('pages.faq');
    
    Route::get('/articles', 'PagesController@articles')->name('pages.articles');
    
    Route::get('/articles/{id}', 'PagesController@article')->name('pages.articles.show');
    
    Route::get('/news', 'PagesController@news')->name('pages.news');
    
});

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth', 'admin']
], function() {
   
    Route::get('/', 'AdminController@index')->name('admin.index');
    
    Route::resource('/news', 'NewsController');
    Route::resource('/articles', 'ArticleController');
    Route::resource('/faq', 'FaqController');
    Route::resource('/hospitals', 'HospitalController');
    Route::resource('/categories', 'CategoryController');
    Route::get('/services/get_by_category', 'ServiceController@getByCategory');
    Route::resource('/services', 'ServiceController');
    Route::resource('/bundles', 'BundleController');
    Route::post('/bundles/{id}/duplicate', 'BundleController@duplicate')->name('bundles.duplicate');
    Route::resource('/users', 'UserController');
    Route::resource('/cities', 'CityController');
    Route::resource('/orders', 'OrdersController', ['except' => ['create', 'store']]);
    
});

Route::get('/hospitals/get-by-city', 'HospitalController@getByCityId')->name('hospitals.get-by-city');
Route::get('/services/get-by-service-category', 'ServiceController@getByServiceCategoryId')->name('services.get-by-service-category');

app/Bundle.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Service;
use App\Hospital;

class Bundle extends Model
{
    public function services() {
        return $this->belongsToMany(Service::class);
    }
    
    public function hospital() {
        return $this->belongsTo(Hospital::class);
    }
}

app/Http/Controllers/BundleController.php
<?php

namespace App\Http\Controllers;

use App\Hospital;
use Illuminate\Http\Request;
use App\Service;
use App\Bundle;

class BundleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bundles = Bundle::all();
        return view('admin.bundles.index', ['bundles' => $bundles]);
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $input = $request->all();
        
        $hospital = Hospital::find($input['hospital_id']);
    
        $services = Service::where('category_id', $hospital['category_id'])->get();
        
        return view('admin.bundles.create', [
            'services' => $services,
            'hospital' => $hospital
        ]);
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        
        $bundle = new Bundle();
    
        $bundle->name = $input['name'];
        $bundle->description = $input['description'];
        $bundle->goal = $input['goal'];
        $bundle->notes = $input['notes'];
        $bundle->price_male = $input['price_male'];
        $bundle->price_female = $input['price_female'];
        $bundle->class = $input['class'];
        $bundle->hospital()->associate($input['hospital_id']);
    
        $bundle->save();
    
        $bundle->services()->sync($input['services']);
        
        return redirect()->route('hospitals.edit', ['id' => $input['hospital_id']]);
    }
    
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, Request $request)
    {
        $input = $request->all();
        
        $bundle = Bundle::with('services')->where('id', '=', $id)->first();
    
        $hospital = Hospital::find($input['hospital_id']);
    
        $services = Service::where('category_id', $hospital['category_id'])->get();
        
        return view('admin.bundles.edit', [
            'bundle' => $bundle,
            'services' => $services,
            'hospital' => $hospital
        ]);
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = $request->all();
        
        $bundle = Bundle::find($id);
        
        $bundle->name = $input['name'];
        $bundle->description = $input['description'];
        $bundle->notes = $input['notes'];
        $bundle->price_male = $input['price_male'];
        $bundle->price_female = $input['price_female'];
        $bundle->class = $input['class'];
        
        $bundle->save();
        
        $bundle->services()->sync($input['services']);
        
        return redirect()->route('hospitals.edit', ['id' => $input['hospital_id']]);
    }
    
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Bundle::destroy($id);
        return back();
    }
    
    /**
     * Duplicate the specified bundle in the database
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function duplicate($id)
    {
        $old_bundle = Bundle::find($id);
        
        $service_ids = [];
        
        foreach ($old_bundle->services as $service) {
            $service_ids[] = $service['id'];
        }
        
        $new_bundle = $old_bundle->replicate();
        
        $new_bundle->save();
        
        $new_bundle->services()->sync($service_ids);
        
        return back();
    }
}

resources/views/admin/bundles/create.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <h1>Create Bundle</h1>

        <form action="{{ route('bundles.store') }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('POST') }}

            <div class="form-group">
                <label for="hospital-name">Госпиталь</label>
                <input type="text" id="hospital-name" class="form-control" value="{{ $hospital['name'] }}" disabled>
                <input type="hidden" name="hospital_id" value="{{ $hospital['id'] }}">
            </div>

            <div class="form-group">
                <label for="bundle-name">Название</label>
                <input type="text" name="name" id="bundle-name" class="form-control">
            </div>

            <div class="form-group">
                <label for="bundle_class">Название</label>
                <select name="class" id="bundle_class">
                    <option value="standard">Стандартный</option>
                    <option value="detailed">Детальный</option>
                    <option value="specialized">Специализированный</option>
                    <option value="premuim">Премиум</option>
                </select>
            </div>

            <div class="form-group">
                <label for="bundle-goal">Цель</label>
                <input type="text" name="goal" id="bundle-goal" class="form-control">
            </div>

            <div class="form-group">
                <label for="bundle-description">Описание</label>
                <textarea rows="10" name="description" id="bundle-description" class="form-control html-editor"></textarea>
            </div>

            <div class="form-group">
                <label for="bundle-notes">Примечания</label>
                <textarea rows="10" name="notes" id="bundle-notes" class="form-control html-editor"></textarea>
            </div>

            <div class="row">
                <h2>Услуги</h2>
                <div class="form-group col-md-4">
                    <h3>Дефолтные</h3>
                    <button id="js-uncheck-default-services" class="btn btn-default">Снять дефолтные чекбоксы</button>
                    @foreach($services as $service)
                        @if($service['type'] == 'default')
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" class="js-default-services" name="services[]" value="{{ $service['id'] }}" checked>
                                    {{ $service['name_ru'] }}
                                </label>
                            </div>
                        @endif
                    @endforeach
                </div>

                <div class="form-group col-md-4">
                    <h3>Популярные</h3>
                    @foreach($services as $service)
                        @if($service['type'] == 'popular')
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="services[]" value="{{ $service['id'] }}">
                                    {{ $service['name_ru'] }}
                                </label>
                            </div>
                        @endif
                    @endforeach
                </div>

                <div class="form-group col-md-4">
                    <h3>Прочие</h3>
                    @foreach($services as $service)
                        @if($service['type'] == null)
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="services[]" value="{{ $service['id'] }}">
                                    {{ $service['name_ru'] }}
                                </label>
                            </div>
                        @endif
                    @endforeach
                </div>
            </div>

            <div class="form-group">
                <label for="">Цена (муж)</label>
                <input type="text" class="form-control" name="price_male">
            </div>

            <div class="form-group">
                <label for="">Цена (жен)</label>
                <input type="text" class="form-control" name="price_female">
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>
    </section>
@endsection

resources/views/admin/bundles/edit.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <h1>Edit Bundle</h1>

        <form action="{{ route('bundles.update', ['id' => $bundle['id']]) }}" method="POST">
            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <input type="hidden" name="hospital_id" value="{{ $hospital['id'] }}">

            <div class="form-group">
                <label for="hospital-name">Госпиталь</label>
                <input type="text" id="hospital-name" class="form-control" value="{{ $hospital['name'] }}" disabled>
                <input type="hidden" name="hospital_id" value="{{ $hospital['id'] }}">
            </div>

            <div class="form-group">
                <label for="bundle-name">Название</label>
                <input type="text" name="name" id="bundle-name" class="form-control" value="{{ $bundle['name'] }}">
            </div>

            <div class="form-group">
                <label for="bundle_class">Класс</label>
                <select name="class" id="bundle_class" class="form-control">
                    <option value="standard" {{ $bundle->class == 'standard' ? 'selected':'' }}>Стандартный</option>
                    <option value="detailed" {{ $bundle->class == 'detailed' ? 'selected':'' }}>Детальный</option>
                    <option value="specialized" {{ $bundle->class == 'specialized' ? 'selected':'' }}>Специализированный</option>
                    <option value="premuim" {{ $bundle->class == 'specific' ? 'selected':'' }}>Премиум</option>
                </select>
            </div>

            <div class="form-group">
                <label for="bundle-goal">Цель</label>
                <input type="text" name="goal" id="bundle-goal" class="form-control" value="{{ $bundle['goal'] }}">
            </div>

            <div class="form-group">
                <label for="bundle-description">Описание</label>
                <textarea rows="10" name="description" id="bundle-description" class="form-control html-editor">{{ $bundle['description'] }}</textarea>
            </div>

            <div class="form-group">
                <label for="bundle-notes">Примечания</label>
                <textarea rows="10" name="notes" id="bundle-notes" class="form-control html-editor">{{ $bundle['notes'] }}</textarea>
            </div>

            <div class="row">
                <h2>Услуги</h2>
                <div class="form-group col-md-4">
                    <h3>Дефолтные</h3>
                    @foreach($services as $service)
                        @if($service['type'] == 'default')
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="services[]" value="{{ $service['id'] }}"
                                           @if($bundle->services->contains('id', $service['id']))
                                           checked
                                            @endif
                                    >
                                    {{ $service['name_ru'] }}
                                </label>
                            </div>
                        @endif
                    @endforeach
                </div>

                <div class="form-group col-md-4">
                    <h3>Популярные</h3>
                    @foreach($services as $service)
                        @if($service['type'] == 'popular')
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="services[]" value="{{ $service['id'] }}"
                                           @if($bundle->services->contains('id', $service['id']))
                                           checked
                                            @endif
                                    >
                                    {{ $service['name_ru'] }}
                                </label>
                            </div>
                        @endif
                    @endforeach
                </div>

                <div class="form-group col-md-4">
                    <h3>Прочие</h3>
                    @foreach($services as $service)
                        @if($service['type'] == null)
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="services[]" value="{{ $service['id'] }}"
                                           @if($bundle->services->contains('id', $service['id']))
                                           checked
                                            @endif
                                    >
                                    {{ $service['name_ru'] }}
                                </label>
                            </div>
                        @endif
                    @endforeach
                </div>
            </div>

            <div class="form-group">
                <label for="">Цена (муж)</label>
                <input type="text" class="form-control" name="price_male" value="{{ $bundle['price_male'] }}">
            </div>

            <div class="form-group">
                <label for="">Цена (жен)</label>
                <input type="text" class="form-control" name="price_female" value="{{ $bundle['price_female'] }}">
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </form>
    </section>
@endsection

resources/views/admin/bundles/index.blade.php
@extends('layouts.app')

@section('content')
    <section>
        <h1>Bundles</h1>

        <div class="form-group">
            <a href="{{ route('bundles.create') }}" class="btn btn-primary">Создать</a>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td>Название</td>
                    <td>Описание</td>
                    <td>Редактировать</td>
                    <td>Дублировать</td>
                    <td>Удалить</td>
                </tr>
            </thead>

            <tbody>
                @foreach($bundles as $bundle)
                    <tr>
                        <td>{{ $bundle['name'] }}</td>
                        <td>{{ $bundle['description'] }}</td>
                        <td><a class="btn btn-primary" href="{{ route('bundles.edit', ['id' => $bundle['id'], 'hospital_id' => $bundle['hospital_id']]) }}">Редактировать</a></td>
                        <td>
                            <form action="{{ route('bundles.duplicate', ['id' => $bundle['id']]) }}" method="POST">
                                {{ method_field('POST') }}
                                {{ csrf_field() }}
                                <input type="submit" class="btn btn-primary" value="Дублировать">
                            </form>
                        </td>
                        <td>
                            <form action="{{ route('bundles.destroy', ['id' => $bundle['id']]) }}" method="POST">
                                {{ method_field('DELETE') }}
                                {{ csrf_field() }}
                                <input type="submit" class="btn btn-danger" value="Удалить">
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </section>
@endsection